### ISSUE TITLE
question: why are intensity values scaled from 0.0 to 1.0 ?

### ISSUE THREAD

**Issue by dancergraham** [cry-inc/e57#13]
Comparing intensity values via this lib with those exported from cloud compare I get the impression (not yet certain) that this library rescales them from 0 at the minimum value to 1 at the maximum value whereas cloud compare gives values the raw values scaled e.g. from 0.395.... to 0.554...
Is this lib rescaling the values on read rather than providing raw intensity values as saved in the e57 file? I'm trying to write sensible tests and documentation for the python wrapper library.

**Comment by dancergraham** [comment]
The pye57 library returns the "actual" intensity values without rescaling to the range 0 to 1, which seems more useful. As that wraps the libe57Format library, I think that is the choice from libe57Format. 

I can see a theoretical advantage in returning values 0 to 1 - it lets you better differentiate close values, giving you finer resolution on the intensity data but I can't see how that is a real world advantage - providing the "actual" values seems more useful.

**Comment by cry-inc** [comment]
I was unsure how to handle intensity when I implemented the simple reader...

The E57 spec does not define any kind of range or unit. It just says
> Point response intensity. Unit is unspecified.

and

> The intensity element shall encode the strength of the signal for a point. The intensity value shall not include compensation for signal strength reduction as a function of distance, surface orientation, or other properties of the surface being sensed.

It does allow any integer and floating point values for intensity.

Other specs, like the one from LAS are more specific and define integers with a 16-bit range:

> Intensity, when included, is always normalized to a 16 bit, unsigned value by multiplying the value by 65536/(intensity dynamic range of the sensor). For example, if the dynamic range of the sensor is 10 bits, the scaling value would be (65536/1024). This normalization is required to ensure that data from different sensors can be correctly merged.

I think the last part with the normalization to uniformly handle data from different devies is important. I wanted to do the same, but since E57 also allows the intensity data to be floats I normalized to 0 to 1 instead of 0 to 65536 to keep more precision.

Normalization can be done in three ways:
1) Using the intensity limits of the E57 point cloud header. They define the range of the sensor that recorded the dataset. The limits are optional and we cannot always rely on them being there.
2) Using the range of the type defined to store the intensity value. Caution: They might be much bigger than the actual range of the sensor!
3) Using the min and max value of the actual intensity values of the E57 point cloud. Requires to read the whole point cloud before we can normalize, which is very problematic for big point clouds. Also the max and min values of a point cloud are not always representing the actual range of the sensor!

This library currently uses the second option. I think it should use the first option with the second as fallback, if the limits are missing. Also, the simple reader should continue to work without having to read the file twice. This means its not an option I want to consider, especially because it would ignore the actual range of the sensor.

For the reason quoted in the LAS spec I also want to continue to normalize the values. But I am open to doing it different or making it optional. We could for example add an option to the simpler reader that forwards the intensity as is, without normalization.

I would be also open to use a different normalized range, for example one that matches LAS, even if it means that we could loose some precision. So far I have never seen floating point intensity values in any actual E57 files.

What do you think?

**Comment by dancergraham** [comment]
>  I think it should use the first option with the second as fallback

I agree - this definitely makes sense to me. If the file doesn't specify the sensor range then the only other way to know would be to maintain a list of ranges of all known sensors, which defeats the point of a transferable file standard! 

>  the max and min values of a point cloud are not always representing the actual range of the sensor!

They usually shouldn't unless you have the sun and a black hole in your field of view, in which case you have bigger problems than file normalisation :) 

> For the reason quoted in the LAS spec I also want to continue to normalize the values

I can see the justification for normalisation on file saving. I think de-normalising on file reading makes sense, particularly for the simple reader. 

> So far I have never seen floating point intensity values in any actual E57 files 

I have some here. - I think Cloud Compare saves intensity values as floating points.  ... 
https://github.com/dancergraham/e57-python/blob/main/testdata/pipeSpherical.e57

**Comment by cry-inc** [comment]
Just released the new version 0.11.7 with improved normalization features and the option to turn it off. Hope this allows you to do what you want :)

**Comment by dancergraham** [comment]
Awesome thank you very much - I was struggling with how to handle an enum of different data types for the min and max values !

**Comment by cry-inc** [comment]
> does the e57 library have different code branches for those platforms somewhere?

No, there are no special code paths for those platforms.

I just added MacOS builds and tests for AArch64 and x86-64 to the library and everything seems to work fine as expected: fd7427490d82b4bfbcdb4ecb5f5ac646be9769f2

Adding Linux AArch64 builds is not as easy, since there seem to be no Arm runners for open source projects available. And I did not want to bother with emulation. If such runners become available, I will try to add support for them as well.

Looking at the log files you linked the Linux AArch64 issue does not seem to be related to Rust and the e57 library but to some Docker issues?

And for the MacOS case, do you by an chance directly compare hardcoded floating point values in the tests? If yes, how much are they off? Sometimes running the same code on a different HW or with different compiler settings yields slightly different floating points results.

**Comment by dancergraham** [comment]
Ahh yes good point on Aarch64 - I will have a look for another fix for that one
The MacOS case is strange - I am getting the same intensity values logged as before you added the option of not normalising - it is not a floating point rounding error. I thought maybe a strange GitHub actions cacheing error but the other log messages suggest it is using the latest code.  I'm sure I've done something foolish somewhere but I can't find it yet.

**Comment by dancergraham** [comment]
OK updating the GitHub actions runners to the latest recommended versions seems to have fixed both errors with no code changes! 
My Aarch64 build uses a ubuntu latest image with the ghcr.io/rust-cross/manylinux2014-cross:aarch64 Docker image - this is handled by the PyO3/maturin-action@v1 which is maintained by the main community project for wrapping rust with Python so should be pretty robust if you want to have a look at adding it.

**Comment by cry-inc** [comment]
Your comment about the Docker image for cross compilation motivated me and I found a easy solution for adding Linux AArch64 builds and tests using https://github.com/cross-rs/cross!

Its a replacement command for cargo and magically takes care of loading any required Docker images and code execution in QEMU etc.
