### ISSUE TITLE
High-level interface

### ISSUE THREAD

**Issue by dancergraham** [cry-inc/e57#3]
Hello,

Working with the code to make a Python wrapper I realise it would be nice to have a high level interface - some convenience functions such as an iterator (getter) providing all the points in cartesian coordinates, an iterator over all the scans, each providing its own iterator over the points.

**Comment by cry-inc** [comment]
Agreed, this makes sense. The early versions had such an "simple" interator for points that just returned a predefined struct with simple doubles for XYZ and floats for RGB etc. I removed it when I added the full direct access for the original values. It needs to come back because this is very useful for many cases were you do not want to deal with the many different low level representations.

**Comment by cry-inc** [comment]
Today I released version [0.6.0](https://crates.io/crates/e57/0.6.0) that now includes a [simple iterator](https://docs.rs/e57/0.6.0/e57/struct.PointCloudReaderSimple.html). I also updated the e57-to-xyz example to use it. It has also a few convenience options to help with typical requirements. It can for example apply the pose automatically to the Cartesian coordinates, skip invalid coordinates, convert spherical to Cartesian coordinates or fall back on intensity as color replacement.

Hope this is aligned with what you imagined!
