### ISSUE TITLE
Read a file containing a transform

### ISSUE THREAD

**Issue by dancergraham** [cry-inc/e57#4]
Hello, 
When converting a file which contains a transform (transslation and rotation) using the e57-to-xyz tool it does not seem to apply the translation and rotation.
I can provide a sample file if needed

**Comment by dancergraham** [comment]
[segmented_transformed.zip](https://github.com/cry-inc/e57/files/12279331/segmented_transformed.zip)

**Comment by cry-inc** [comment]
Yes! I wanted to do this for a long time, but always postponed it.

I used the opportunity to also extend the tool to convert points from all point clouds in the E57 file (and not only the first one).

You can find the changes in commit 1656b609a29ef3bb8f8d2451bacbcc795a22ab3a. Keep in mind that this code might not yet work with the latest release 0.5.1 since it requires some convenience changes that are currently only available in master.

I tested it with example #7 from http://www.libe57.org/data.html. That file contains multiple scans with rotations and translations.
